-- CreateEnum
CREATE TYPE "Subject" AS ENUM ('MATHEMATIQUES', 'FRANCAIS', 'HISTOIRE_GEOGRAPHIE', 'SCIENCES', 'PHYSIQUE_CHIMIE', 'SVT', 'TECHNOLOGIE', 'ANGLAIS', 'ESPAGNOL', 'ALLEMAND', 'PHILOSOPHIE', 'ECONOMIE', 'SES', 'INFORMATIQUE', 'ARTS_PLASTIQUES', 'MUSIQUE', 'EPS', 'EMC', 'LATIN', 'GREC', 'AUTRE');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "subject" "Subject",
ADD COLUMN     "subjectOther" TEXT;
